### ISSUE TITLE
README.md: Documentation points to internal address (auth needed)

### ISSUE THREAD

**Issue by sirtobey** [adfinis-sygroup/pyaptly#1]
As in title, following the "Documentation" link will lead to an address, where authentication is needed and probably isn't meant for the public.

I do not think this is intentional..

**Comment by ganwell** [comment]
Yes I have to change to Readthedocs. Will be done soonish :-)

**Comment by sirtobey** [comment]
Awesome, no hurry. I just wanted to make sure you were aware. ;)
