### ISSUE TITLE
add possibility to configure gpg-key for a publish

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/pyaptly#13]
Aptly offers the possibility to pass the gpg key to use for signing the publish as an option `-gpg-key`.
This should be added as a possible configuration in the pyaptly yaml file.

**Comment by ganwell** [comment]
@tongpu actually its implemented only the documentation was missing. I close that for now. Please check the new documentation and reopen the issue if needed. Fixed by #15
