### ISSUE TITLE
Ubuntu repo empty?

### ISSUE THREAD

**Issue by jalmansor** [adfinis-sygroup/pyaptly#38]
I recently found your project while struggling to sanely implement aptly with weekly snapshots for different environments. However, while trying to install it on ubuntu (xenial), I came to realize that the repo is actually empty. I am saddened greatly.

**Comment by ganwell** [comment]
@jalmansor It seems like somebody cleared out the repos and I'll do a re-release on Tuesday.

@eni23 @karras ??

**Comment by karras** [comment]
@jalmansor thanks for reporting it! I just republished the repos, can you please try again?
